#!/bin/sh

echo test >/home/simon/init_test

setbg &		# Set the background
sxhkd &		# Bind keys

# Switch to US international with Caps as Mod/Escape
setxkbmap -option caps:super -variant altgr-intl && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &

# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
#picom 2>$ERROR/picom &		# xcompmgr for transparency
pgrep "dunst" >/dev/null && dunst &			# dunst for notifications
/usr/lib/kdeconnectd
jami -r &
#mpdupdate &

