#!/bin/bash

# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm
echo bspwm >/home/simon/bspwmworks

#### AUTOSTART ####  Programs seem to autostart in .xprofile instead
#sxhkd 2>"$ERROR"/sxhkd &
#compton  2>"$ERROR"/compton &
#nitrogen --restore  2>"$ERROR"/nitrogen &
#setbg &
#bspc monitor VGA1 -d 6 7 8 9 10
[ ! -d /tmp/bspwmscript ] && mkdir /tmp/bspwmscript

#[ -n "$(xrandr -q | grep " connected" | grep "VGA1")" ] && xrandr --output "$primary" --auto --scale 1.0x1.0 --output "$secondary" --"$side"-of "$primary" --auto --scale 1.0x1.0 2>"$ERROR"/bspwmrc_xrandr &
# Script for screen configuration (The proper way)
# init_screen 2>"$ERROR"/init_screen &

#### BSPWM configuration ####
bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   23
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
#bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
#bspc config normal_border_color		"#d8d8d8"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

# polybar hidden when fullscreen for vlc, youtube, mpv ...
# find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Confirmation
#echo "works" > "$ERROR"/bspwmtest
